---
blank_issues_enabled: false
contact_links:
  - name: Ask a question (GitHub Discussions)
    url: https://github.com/winder/Universal-G-Code-Sender/discussions
    about: Ask a question or request support for using Universal Gcode Sender.
  - name: Discord server
    url: https://discord.com/invite/4DYywtyGYK
    about: Ask and answer questions on our Discord server.
